package com.backend.sporta.enums;

public enum NotificationType {
    // MATCH
    MATCH_INVITE,
    MATCH_REQUEST_JOIN,
    MATCH_JOIN_ACCEPTED,
    MATCH_JOIN_REJECTED,
    MATCH_REMINDER,
    MATCH_CANCELLED,

    // BOOKING
    BOOKING_SUCCESS,
    BOOKING_CANCELLED,
    BOOKING_REMINDER,

    // TICKET (VE LE)
    TICKET_PURCHASE_SUCCESS,
    TICKET_SESSION_CANCELLED,
    TICKET_CHECKIN_SUCCESS,

    // CLUB
    CLUB_INVITE,
    CLUB_JOIN_REQUEST,
    CLUB_JOIN_ACCEPTED,

    // SOCIAL
    POST_LIKED,
    POST_COMMENTED,

    // WALLET & VOUCHER
    WALLET_DEPOSIT_SUCCESS,
    VOUCHER_RECEIVED,

    // SUPPORT
    TICKET_REPLIED,

    // OWNER
    OWNER_NEW_BOOKING,
    OWNER_BOOKING_CANCELLED,
    OWNER_NEW_REVIEW,
    OWNER_VENUE_APPROVED,
    OWNER_VENUE_REJECTED,
    OWNER_REVISION_APPROVED,
    OWNER_WITHDRAWAL_APPROVED,
    OWNER_WITHDRAWAL_REJECTED,
    OWNER_TICKET_BOUGHT,

    // ADMIN
    ADMIN_NEW_VENUE_AUDIT,
    ADMIN_VENUE_REVISION,
    ADMIN_NEW_OWNER_REGISTER,
    ADMIN_WITHDRAWAL_REQUEST,
    ADMIN_PAYMENT_DISPUTE,
    ADMIN_NEW_SUPPORT_TICKET,
    ADMIN_REPORT_VIOLATION,
    SUPPORT_TICKET_NEW,
    SUPPORT_TICKET_UPDATED,

    // SYSTEM
    PROMOTION,
    SYSTEM_ALERT
}