server.port=8080

spring.application.name=sporta

spring.datasource.url=jdbc:postgresql://localhost:5432/sporta_database
spring.datasource.username=sporta_dev
spring.datasource.password=sporta_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hethongthethaosporta@gmail.com
spring.mail.password=rlcs eypo lgju xfwu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=9A3287B97A0A955B5A1A5B450098F3B0E8D7F9B1C2A3D4E5F6A7B8C9D0E1F2A3
app.jwt.expiration-ms=86400000
