server:
  port: 8080

spring:
  application:
    name: sporta
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sporta_database
    username: sporta_dev
    password: sporta_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hethongthethaosporta@gmail.com
    password: rlcs eypo lgju xfwu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: 9A3287B97A0A955B5A1A5B450098F3B0E8D7F9B1C2A3D4E5F6A7B8C9D0E1F2A3
    expiration-ms: 86400000 # 24 hours
